name: PR comment & label check 

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  Looking_for_labels:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN}}

      - name: Check labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: version:major,version:minor,version:patch,no_release
          mode: exactly
          count: 1
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  reminder_comment:
    needs: Looking_for_labels
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ':bangbang: This is github action reminder. :bangbang: When you make a PR on the main branch, you have to choose exactly one label.'
